version: '3.1'

services:
  db:
    image: postgres:15.1
    restart: always
    environment:
      POSTGRES_PASSWORD: dbpass
      POSTGRES_USER: dbuser
      POSTGRES_DB: anki
    ports:
      - "5432:5432"

#  cmd:
#    image: dann41/anki-cmd:0.0.1
#    stdin_open: true
#    tty: true
#    volumes:
#      - /Users/daniel.gomez/personal/projects/anki/core/src/main/resources/collections:/collections
#    environment:
#      SPRING_PROFILES_ACTIVE: pro
