spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/anki
    username: dbuser
    password: dbpass
    hikari:
      maximum-pool-size: 10
      minimum-idle: 4
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
  flyway:
    locations: classpath:db/migrations
    enabled: true