spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/anki
    username: dbuser
    password: dbpass
    hikari:
      maximum-pool-size: 10
      minimum-idle: 4
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
  flyway:
    locations: classpath:db/migrations
    enabled: true

jwt:
  private-key: |
    -----BEGIN PRIVATE KEY-----
    MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQDHIKIwifNSyxbd
    U/GJrPM3+pfdARdNzoAcHGO/RnAs9gxJ2mD6KL6Tf1F2jri66A+icIs/tM0glrqH
    nbnsYF0ah58QcYjpcuBusDol7INqM87cxHN97EHXqeIpC7/XUu7adnxETxTB2aw+
    TC5L5DEk5VG/JXF4KR35ULLzVMNA+e+GRVwNqQtphWjjZRDf9YoalEbIEmc0xS0n
    7XKRIA5JUp2gzhdd+fc+kLUcVzAPEOagrwUlUPeoYfg00qUENQnpLHKV3sc/AQMC
    VA1P+RpQEYJ89MLSeqmwSVW4pSGSnmR/hhw/rcWGwN4ZcKlbatkIO0a3HF2VNrKy
    KNY1PN37AgMBAAECggEBAI/Ky/QbGd92kks/G9NcVcHdrp5D9G0WKkKiaZEtL0H4
    Z0VJcfATThM6xDvFsjYd73RQqu1VBS98SLQ3vJOpvnGy77UzFzfk4ZZsoYDTOs6N
    HNsk7XVIDv/KSGt1dZHq7FpLZ074gDe/lPbjkibxYF+RTSenxTmND30CvkaiteCL
    k9IdVkOwpkajP6XA4bwmAEgVpnowtC9cNqwycrkR2TddhBjHIoS/HjIOZpmHExZJ
    5szgCjtHn3SgpN1XHgLMEBKp2x9ivWuJcbS+ZpEezzrUGi5wJo0ZTpHi3KGkv31r
    8qho+k+VOzOC44jWpwzysmoRE2FW1r19r3Qr6OefprECgYEA+E3URg3vbbNorSmp
    m9d57ekzl90tHJ8hqgE9tT3NZEV/G7428nE2jkFwmmuBmzYNiew0Sjme01C9WHFZ
    I402PJeq54Yz004VItBFo+eGGKiWW1vDC7kYkAj+/ROW2C3D9lHRMmEnhV3r/bqh
    K6ZlyEH1YwYH9nkdc1w+Q/UcU3kCgYEAzUyc0EFeXtS3PvaJV4DHUVvWIRKz1ihY
    UOak1wy/raNZ14v9cfzkBhJMzHGykCO6Va9PE2EBRasX6BfA06lCVAvkjt48xnUU
    ScDsaBRzMwW7ksjg5LW7YPhSKPlvXlf5+6YSw0aIkopqrGMw7QH7ESYm6w06SjB2
    dQZTZlLBDBMCgYB+6nkn3ZOWBO/qIrN43qiJ/HrMktauHIB+fuflrdM//2265nz7
    avaxu60soOq8ROKirsMDdXRDGq/NdxJS46jnS7alZKk0xmJzSvVtk7es/u7rf3mw
    kkmFxbNf9BVUJgBV9PfywkoLFzi6lhwvTXwU4fHlTX3gc4OkJXAGGFEEMQKBgQCa
    3Ju9jFG/fv3rhNT9KKsxd/ECabU2aqCUBid6AKfmNz5iFbtM7NKksdE0tt9XU1wP
    nnoryBTJlNInxSMzho3+ECqMip+VpGN1bw3lROfRKRXhF55tZ5i9ARQYzG9x3zM2
    3INywhXrVHY7K2eQoNneicT5sbSymfQBOpBWsz3j+QKBgQDnvwUDVexS19GvRhWO
    LI14tIGx7N3W4ZJHhtmE2TFt1zY3Ec/QmLjrbmrErhcUS4cs4rYOyr3DRrubDlup
    G/E1e0jX3rDTPzhAM5h6+DiQR/X9AJ/A4+Y6Tr3jFAgwR2vuXxbemNmvb6O2pHuP
    xBd740Vn/WwsmBBke1cig5JkeA==
    -----END PRIVATE KEY-----

  public-key: |
    -----BEGIN PUBLIC KEY-----
    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAxyCiMInzUssW3VPxiazz
    N/qX3QEXTc6AHBxjv0ZwLPYMSdpg+ii+k39Rdo64uugPonCLP7TNIJa6h5257GBd
    GoefEHGI6XLgbrA6JeyDajPO3MRzfexB16niKQu/11Lu2nZ8RE8UwdmsPkwuS+Qx
    JOVRvyVxeCkd+VCy81TDQPnvhkVcDakLaYVo42UQ3/WKGpRGyBJnNMUtJ+1ykSAO
    SVKdoM4XXfn3PpC1HFcwDxDmoK8FJVD3qGH4NNKlBDUJ6Sxyld7HPwEDAlQNT/ka
    UBGCfPTC0nqpsElVuKUhkp5kf4YcP63FhsDeGXCpW2rZCDtGtxxdlTaysijWNTzd
    +wIDAQAB
    -----END PUBLIC KEY-----